# netlify.toml (simplified version - no SSR)
[build]
  # Simple client-side build
  command = "nx build root --configuration=production"
  publish = "dist/apps/root/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200