[build]
  # Update with your actual app name
  command = "nx build root"
  publish = "dist/apps/root/browser"

# This tells Netlify to use the new Angular runtime
[build.environment]
  NETLIFY_USE_ANGULAR_UNIVERSAL = "true"

[functions]
  directory = "netlify/edge-functions"
  
[[plugins]]
  package = "@netlify/angular-runtime"