[build]
  command = "nx build root --prod" # Replace app-name with your actual app name
  publish = "dist/apps/root/browser" # Path to your browser dist folder
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200