[build]
  # Update with your actual app name
  command = "nx build root && nx run root:server:production"
  publish = "dist/apps/root/browser"

# This tells Netlify to use the new Angular runtime
[build.environment]
  NETLIFY_USE_ANGULAR_UNIVERSAL = "true"

[[plugins]]
  package = "@netlify/angular-runtime"